In [1]:
import sys
print(sys.executable)

C:\Users\ROG\.conda\envs\detr-gpu\python.exe

In [3]:
import sys
!{sys.executable} -m pip install -U ultralytics opencv-python pyyaml pandas matplotlib

Requirement already satisfied: ultralytics in .\.conda\envs\detr-gpu\lib\site-packages (8.4.21)
Requirement already satisfied: opencv-python in .\.conda\envs\detr-gpu\lib\site-packages (4.13.0.92)
Requirement already satisfied: pyyaml in .\.conda\envs\detr-gpu\lib\site-packages (6.0.3)
Requirement already satisfied: pandas in .\.conda\envs\detr-gpu\lib\site-packages (2.3.3)
Requirement already satisfied: matplotlib in .\.conda\envs\detr-gpu\lib\site-packages (3.10.8)
Requirement already satisfied: numpy>=1.23.0 in .\.conda\envs\detr-gpu\lib\site-packages (from ultralytics) (2.2.6)
Requirement already satisfied: pillow>=7.1.2 in .\.conda\envs\detr-gpu\lib\site-packages (from ultralytics) (12.0.0)
Requirement already satisfied: requests>=2.23.0 in .\.conda\envs\detr-gpu\lib\site-packages (from ultralytics) (2.32.5)
Requirement already satisfied: scipy>=1.4.1 in .\.conda\envs\detr-gpu\lib\site-packages (from ultralytics) (1.15.3)
Requirement already satisfied: torch>=1.8.0 in .\.conda\envs\detr-gpu\lib\site-packages (from ultralytics) (2.5.1+cu121)
Requirement already satisfied: torchvision>=0.9.0 in .\.conda\envs\detr-gpu\lib\site-packages (from ultralytics) (0.20.1+cu121)
Requirement already satisfied: psutil>=5.8.0 in .\.conda\envs\detr-gpu\lib\site-packages (from ultralytics) (7.2.2)
Requirement already satisfied: polars>=0.20.0 in .\.conda\envs\detr-gpu\lib\site-packages (from ultralytics) (1.38.1)
Requirement already satisfied: ultralytics-thop>=2.0.18 in .\.conda\envs\detr-gpu\lib\site-packages (from ultralytics) (2.0.18)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.conda\envs\detr-gpu\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\.conda\envs\detr-gpu\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in .\.conda\envs\detr-gpu\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in .\.conda\envs\detr-gpu\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in .\.conda\envs\detr-gpu\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in .\.conda\envs\detr-gpu\lib\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in .\.conda\envs\detr-gpu\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in .\.conda\envs\detr-gpu\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pyparsing>=3 in .\.conda\envs\detr-gpu\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: polars-runtime-32==1.38.1 in .\.conda\envs\detr-gpu\lib\site-packages (from polars>=0.20.0->ultralytics) (1.38.1)
Requirement already satisfied: six>=1.5 in .\.conda\envs\detr-gpu\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in .\.conda\envs\detr-gpu\lib\site-packages (from requests>=2.23.0->ultralytics) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in .\.conda\envs\detr-gpu\lib\site-packages (from requests>=2.23.0->ultralytics) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in .\.conda\envs\detr-gpu\lib\site-packages (from requests>=2.23.0->ultralytics) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in .\.conda\envs\detr-gpu\lib\site-packages (from requests>=2.23.0->ultralytics) (2026.2.25)
Requirement already satisfied: filelock in .\.conda\envs\detr-gpu\lib\site-packages (from torch>=1.8.0->ultralytics) (3.20.0)
Requirement already satisfied: typing-extensions>=4.8.0 in .\.conda\envs\detr-gpu\lib\site-packages (from torch>=1.8.0->ultralytics) (4.15.0)
Requirement already satisfied: networkx in .\.conda\envs\detr-gpu\lib\site-packages (from torch>=1.8.0->ultralytics) (3.4.2)
Requirement already satisfied: jinja2 in .\.conda\envs\detr-gpu\lib\site-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec in .\.conda\envs\detr-gpu\lib\site-packages (from torch>=1.8.0->ultralytics) (2025.12.0)
Requirement already satisfied: sympy==1.13.1 in .\.conda\envs\detr-gpu\lib\site-packages (from torch>=1.8.0->ultralytics) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in .\.conda\envs\detr-gpu\lib\site-packages (from sympy==1.13.1->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in .\.conda\envs\detr-gpu\lib\site-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.2)

In [5]:
data_yaml = """
path: C:/Users/ROG/Desktop/Datasets_with_annotation_object_detection/Merged_dataset
train: images/train
val: images/val
test: images/test

names:
  0: Interphase
  1: Prophase
  2: Lateprophase
  3: Metaphase
  4: Anaphase
  5: Lateanaphase
  6: Telophase
"""

yaml_path = r"C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\data.yaml"

with open(yaml_path, "w", encoding="utf-8") as f:
    f.write(data_yaml)

print("Saved:", yaml_path)

Saved: C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\data.yaml

In [7]:
import os, glob

base = r"C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset"

for p in [
    os.path.join(base, "images", "train"),
    os.path.join(base, "images", "val"),
    os.path.join(base, "images", "test"),
    os.path.join(base, "labels", "train"),
    os.path.join(base, "labels", "val"),
    os.path.join(base, "labels", "test"),
]:
    print(p, "->", os.path.exists(p))

for split in ["train", "val", "test"]:
    imgs = []
    for ext in ("*.jpg", "*.jpeg", "*.png", "*.bmp", "*.tif", "*.tiff"):
        imgs.extend(glob.glob(os.path.join(base, "images", split, ext)))
    lbls = glob.glob(os.path.join(base, "labels", split, "*.txt"))
    print(split, "images:", len(imgs), "labels:", len(lbls))

C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\train -> True
C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\val -> True
C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test -> True
C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\train -> True
C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val -> True
C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\test -> True
train images: 364 labels: 364
val images: 91 labels: 91
test images: 47 labels: 47

In [9]:
from ultralytics import YOLO

model = YOLO("yolov8n-obb.pt")   # or another available -obb checkpoint in your installed version

In [11]:
from ultralytics import YOLO
from pathlib import Path
import os
import traceback

RUN_PROJECT = "runs_obb"
RUN_NAME = "obb_baseline_832_ep100"

model = YOLO("yolov8n-obb.pt")

try:
    results = model.train(
        data=yaml_path,
        epochs=100,
        imgsz=832,
        batch=8,
        device=0,
        project=RUN_PROJECT,
        name=RUN_NAME,
        save=True,
        exist_ok=True,
        verbose=True
    )
except Exception:
    print("Training crashed:")
    traceback.print_exc()

weights_dir = Path(RUN_PROJECT) / RUN_NAME / "weights"
best_path = weights_dir / "best.pt"
last_path = weights_dir / "last.pt"

print("\nWeights directory:", weights_dir)
print("Weights dir exists:", weights_dir.exists())

if weights_dir.exists():
    print("Available files:", os.listdir(weights_dir))

model_path = None
if best_path.exists():
    model_path = best_path
elif last_path.exists():
    model_path = last_path

if model_path is not None:
    print(f"\nUsing weights: {model_path}")
    eval_model = YOLO(str(model_path))
    metrics = eval_model.val(data=yaml_path)

    p = metrics.box.p
    r = metrics.box.r
    map50 = metrics.box.map50
    map5095 = metrics.box.map
    f1 = 2 * p * r / (p + r + 1e-16)

    print(f"Precision   : {p}")
    print(f"Recall      : {r}")
    print(f"mAP50       : {map50}")
    print(f"mAP50-95    : {map5095}")
    print(f"F1 Score    : {f1}")
else:
    print("\nNo best.pt or last.pt found. Training likely failed before checkpoint saving completed.")

Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=100, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=832, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n-obb.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=obb_baseline_832_ep100, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=runs_obb, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\ROG\runs\obb\runs_obb\obb_baseline_832_ep100, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=obb, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=15 with nc=7

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    824344  ultralytics.nn.modules.head.OBB              [7, 1, 16, None, [64, 128, 256]]
YOLOv8n-obb summary: 145 layers, 3,083,880 parameters, 3,083,864 gradients, 8.4 GFLOPs

Transferred 391/397 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.10.1 ms, read: 1152.1106.6 MB/s, size: 3834.8 KB)
train: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\train.cache... 364 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 364/364  0.0s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access  (ping: 0.30.0 ms, read: 622.667.0 MB/s, size: 4080.1 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000909, momentum=0.9) with parameter groups 63 weight(decay=0.0), 73 weight(decay=0.0005), 72 bias(decay=0.0)
Plotting labels to C:\Users\ROG\runs\obb\runs_obb\obb_baseline_832_ep100\labels.jpg...
Image sizes 832 train, 832 val
Using 8 dataloader workers
Logging results to C:\Users\ROG\runs\obb\runs_obb\obb_baseline_832_ep100
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      1/100      3.08G      1.445      3.895      1.991     0.3029        123        832: 100% ━━━━━━━━━━━━ 46/46 2.9it/s 16.1s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.9it/s 1.7s0.1s
                   all         91       2188      0.644        0.1     0.0652       0.05

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      2/100      2.78G      1.022       2.37      1.642     0.2246        279        832: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.5s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 9.7it/s 1.2s0.1s
                   all         91       2188      0.226      0.181     0.0937     0.0779

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      3/100      3.17G     0.9305      1.999      1.563     0.2096        145        832: 100% ━━━━━━━━━━━━ 46/46 3.5it/s 13.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 3.3it/s 3.6s0.3s
                   all         91       2188      0.229       0.21      0.115     0.0969

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      4/100      3.15G     0.8962      1.902      1.506     0.2012         94        832: 100% ━━━━━━━━━━━━ 46/46 3.5it/s 13.2s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.9it/s 1.7s0.1s
                   all         91       2188      0.411      0.239      0.149      0.123

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      5/100      2.85G     0.8785      1.734      1.438     0.2299        188        832: 100% ━━━━━━━━━━━━ 46/46 4.2it/s 11.0s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.9it/s 1.7s0.2s
                   all         91       2188      0.444      0.221      0.174      0.143

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      6/100      2.85G     0.8583      1.682      1.364     0.2098        140        832: 100% ━━━━━━━━━━━━ 46/46 3.4it/s 13.4s0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.8it/s 1.8s0.2s
                   all         91       2188      0.454      0.221      0.189      0.156

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      7/100      2.85G     0.8386      1.649       1.34     0.2102        166        832: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 7.0it/s 1.7s0.1s
                   all         91       2188      0.474      0.225       0.22       0.18

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      8/100      2.85G      0.827      1.597      1.324     0.2015        156        832: 100% ━━━━━━━━━━━━ 46/46 4.2it/s 10.9s0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 7.3it/s 1.6s0.1s
                   all         91       2188      0.313      0.248      0.223      0.183

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      9/100      2.85G     0.8106      1.567      1.309     0.2062        128        832: 100% ━━━━━━━━━━━━ 46/46 3.5it/s 13.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.8it/s 1.8s0.1s
                   all         91       2188      0.529      0.259       0.25      0.203

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     10/100      2.85G     0.7808      1.504        1.3     0.1951        290        832: 100% ━━━━━━━━━━━━ 46/46 4.2it/s 11.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 3.3it/s 3.6s0.2s
                   all         91       2188      0.346      0.381      0.253      0.207

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     11/100      2.85G     0.7906      1.518      1.284     0.1947        162        832: 100% ━━━━━━━━━━━━ 46/46 4.4it/s 10.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 3.1it/s 3.9s0.1s
                   all         91       2188      0.344      0.411      0.296      0.239

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     12/100      2.85G     0.7775      1.481      1.285      0.197        140        832: 100% ━━━━━━━━━━━━ 46/46 4.0it/s 11.5s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 3.7it/s 3.3s0.1s
                   all         91       2188      0.379      0.365      0.295      0.237

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     13/100      3.37G     0.7557      1.471      1.277     0.2012        155        832: 100% ━━━━━━━━━━━━ 46/46 3.9it/s 11.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 7.6it/s 1.6s0.1s
                   all         91       2188      0.417      0.346      0.304      0.246

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     14/100      2.53G     0.7499      1.427      1.258     0.1844        238        832: 100% ━━━━━━━━━━━━ 46/46 5.9it/s 7.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 8.0it/s 1.5s0.1s
                   all         91       2188      0.408      0.398      0.341      0.272

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     15/100      2.89G     0.7396      1.393      1.265     0.1904        142        832: 100% ━━━━━━━━━━━━ 46/46 6.0it/s 7.7s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 8.3it/s 1.5s0.1s
                   all         91       2188      0.304       0.47      0.362      0.285

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     16/100      2.89G     0.7554      1.405      1.277     0.1911        124        832: 100% ━━━━━━━━━━━━ 46/46 5.7it/s 8.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.8it/s 1.8s0.1s
                   all         91       2188      0.319      0.471      0.366       0.29

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     17/100      2.89G     0.7479      1.387      1.248     0.1831        222        832: 100% ━━━━━━━━━━━━ 46/46 5.9it/s 7.7s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 7.8it/s 1.5s0.1s
                   all         91       2188      0.338      0.481      0.374      0.295

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     18/100      2.89G     0.7307      1.357      1.247     0.1783        131        832: 100% ━━━━━━━━━━━━ 46/46 6.0it/s 7.7s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 7.9it/s 1.5s0.1s
                   all         91       2188       0.35      0.463      0.381        0.3

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     19/100      2.89G     0.7286      1.355      1.248      0.179        186        832: 100% ━━━━━━━━━━━━ 46/46 5.9it/s 7.7s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 7.9it/s 1.5s0.1s
                   all         91       2188      0.273       0.53      0.371      0.298

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     20/100      3.28G     0.7172      1.346      1.241     0.1708        404        832: 100% ━━━━━━━━━━━━ 46/46 5.3it/s 8.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 8.7it/s 1.4s0.1s
                   all         91       2188      0.536      0.449      0.425      0.336

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     21/100      2.25G     0.7142      1.317      1.226     0.1767        145        832: 100% ━━━━━━━━━━━━ 46/46 5.8it/s 8.0s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 7.6it/s 1.6s0.1s
                   all         91       2188      0.509      0.505      0.424      0.338

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     22/100      2.61G     0.7256      1.348      1.256     0.1727        236        832: 100% ━━━━━━━━━━━━ 46/46 6.0it/s 7.7s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 8.5it/s 1.4s0.1s
                   all         91       2188      0.562        0.5      0.442      0.354

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     23/100      2.99G     0.7179      1.296      1.247     0.1888        406        832: 100% ━━━━━━━━━━━━ 46/46 5.9it/s 7.8s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 8.3it/s 1.4s0.1s
                   all         91       2188       0.55      0.531      0.456      0.358

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     24/100      3.43G     0.7211      1.326      1.246     0.1753        182        832: 100% ━━━━━━━━━━━━ 46/46 4.6it/s 9.9s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 8.1it/s 1.5s0.1s
                   all         91       2188       0.61      0.493      0.472      0.377

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     25/100      2.61G     0.6945      1.257      1.233     0.1739        131        832: 100% ━━━━━━━━━━━━ 46/46 5.8it/s 7.9s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 7.9it/s 1.5s0.1s
                   all         91       2188      0.596      0.541       0.49      0.391

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     26/100      2.97G     0.6899      1.242      1.232     0.1813        115        832: 100% ━━━━━━━━━━━━ 46/46 5.4it/s 8.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 7.3it/s 1.6s0.1s
                   all         91       2188      0.588      0.506      0.471      0.386

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     27/100      2.97G      0.714      1.288      1.232     0.1617        144        832: 100% ━━━━━━━━━━━━ 46/46 4.3it/s 10.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 8.5it/s 1.4s0.1s
                   all         91       2188      0.588       0.54      0.491      0.398

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     28/100       3.4G     0.7015      1.271      1.235      0.176        124        832: 100% ━━━━━━━━━━━━ 46/46 4.2it/s 10.9s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 8.9it/s 1.3s0.1s
                   all         91       2188      0.612      0.547      0.511       0.41

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     29/100      2.12G     0.7002      1.254      1.226      0.166        355        832: 100% ━━━━━━━━━━━━ 46/46 4.2it/s 11.0s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 8.7it/s 1.4s0.1s
                   all         91       2188      0.655      0.519      0.504      0.413

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     30/100      2.48G     0.6981      1.229      1.237     0.1769        412        832: 100% ━━━━━━━━━━━━ 46/46 4.1it/s 11.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 3.5it/s 3.4s0.2s
                   all         91       2188      0.588      0.555       0.52      0.422

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     31/100      2.48G     0.7106      1.258      1.224     0.1678        217        832: 100% ━━━━━━━━━━━━ 46/46 4.9it/s 9.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 4.2it/s 2.9s0.1s
                   all         91       2188      0.631      0.529      0.579      0.471

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     32/100      2.89G     0.7103      1.275      1.225     0.1607        143        832: 100% ━━━━━━━━━━━━ 46/46 4.3it/s 10.6s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 7.7it/s 1.6s0.1s
                   all         91       2188       0.62      0.521      0.516       0.42

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size

In [13]:
from ultralytics import YOLO
from pathlib import Path
import traceback
import os

RUN_PROJECT = "runs_obb"
RUN_NAME = "obb_debug_832_ep100"

model = YOLO("yolov8n-obb.pt")   # use an OBB pretrained model

try:
    results = model.train(
        data=yaml_path,
        epochs=100,
        imgsz=832,
        batch=8,
        device=0,
        project=RUN_PROJECT,
        name=RUN_NAME,
        save=True,
        exist_ok=True,
        verbose=True
    )
    print("Training finished successfully.")

except Exception as e:
    print("\nTRAINING FAILED:")
    traceback.print_exc()

run_dir = Path(RUN_PROJECT) / RUN_NAME
weights_dir = run_dir / "weights"

print("\nRun dir exists:", run_dir.exists())
print("Weights dir exists:", weights_dir.exists())
if weights_dir.exists():
    print("Weights files:", os.listdir(weights_dir))

Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=100, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=832, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n-obb.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=obb_debug_832_ep100, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=runs_obb, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\ROG\runs\obb\runs_obb\obb_debug_832_ep100, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=obb, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=15 with nc=7

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    824344  ultralytics.nn.modules.head.OBB              [7, 1, 16, None, [64, 128, 256]]
YOLOv8n-obb summary: 145 layers, 3,083,880 parameters, 3,083,864 gradients, 8.4 GFLOPs

Transferred 391/397 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.00.0 ms, read: 2050.3606.6 MB/s, size: 3834.8 KB)
train: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\train.cache... 364 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 364/364  0.0s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access  (ping: 0.10.0 ms, read: 979.183.5 MB/s, size: 4080.1 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000909, momentum=0.9) with parameter groups 63 weight(decay=0.0), 73 weight(decay=0.0005), 72 bias(decay=0.0)
Plotting labels to C:\Users\ROG\runs\obb\runs_obb\obb_debug_832_ep100\labels.jpg...
Image sizes 832 train, 832 val
Using 8 dataloader workers
Logging results to C:\Users\ROG\runs\obb\runs_obb\obb_debug_832_ep100
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      1/100      3.15G      1.445      3.895      1.991     0.3029        123        832: 100% ━━━━━━━━━━━━ 46/46 4.7it/s 9.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.1it/s 2.3s0.2s
                   all         91       2188      0.644        0.1     0.0652       0.05

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      2/100      2.79G      1.022       2.37      1.642     0.2246        279        832: 100% ━━━━━━━━━━━━ 46/46 5.7it/s 8.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.4it/s 1.9s0.2s
                   all         91       2188      0.226      0.181     0.0937     0.0779

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      3/100      3.18G     0.9305      1.999      1.563     0.2096        145        832: 100% ━━━━━━━━━━━━ 46/46 4.7it/s 9.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.0it/s 2.4s0.2s
                   all         91       2188      0.229       0.21      0.115     0.0969

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      4/100      3.17G     0.8962      1.902      1.506     0.2012         94        832: 100% ━━━━━━━━━━━━ 46/46 5.7it/s 8.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.6it/s 2.1s0.2s
                   all         91       2188      0.411      0.239      0.149      0.123

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      5/100      2.85G     0.8785      1.734      1.438     0.2299        188        832: 100% ━━━━━━━━━━━━ 46/46 5.9it/s 7.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.8it/s 2.1s0.2s
                   all         91       2188      0.444      0.221      0.174      0.143

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      6/100      2.85G     0.8583      1.682      1.364     0.2098        140        832: 100% ━━━━━━━━━━━━ 46/46 6.0it/s 7.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.8it/s 2.1s0.2s
                   all         91       2188      0.454      0.221      0.189      0.156

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      7/100      2.85G     0.8386      1.649       1.34     0.2102        166        832: 100% ━━━━━━━━━━━━ 46/46 5.5it/s 8.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.8it/s 2.1s0.2s
                   all         91       2188      0.474      0.225       0.22       0.18

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      8/100      2.85G      0.827      1.597      1.324     0.2015        156        832: 100% ━━━━━━━━━━━━ 46/46 6.0it/s 7.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.8it/s 2.1s0.2s
                   all         91       2188      0.313      0.248      0.223      0.183

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      9/100      2.85G     0.8106      1.567      1.309     0.2062        128        832: 100% ━━━━━━━━━━━━ 46/46 5.5it/s 8.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.4it/s 2.2s0.2s
                   all         91       2188      0.529      0.259       0.25      0.203

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     10/100      2.85G     0.7808      1.504        1.3     0.1951        290        832: 100% ━━━━━━━━━━━━ 46/46 4.7it/s 9.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.8it/s 2.1s0.2s
                   all         91       2188      0.346      0.381      0.253      0.207

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     11/100      2.85G     0.7906      1.518      1.284     0.1947        162        832: 100% ━━━━━━━━━━━━ 46/46 5.8it/s 7.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.5it/s 1.9s0.2s
                   all         91       2188      0.344      0.411      0.296      0.239

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     12/100      2.85G     0.7775      1.481      1.285      0.197        140        832: 100% ━━━━━━━━━━━━ 46/46 5.8it/s 8.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.3it/s 1.9s0.2s
                   all         91       2188      0.379      0.365      0.295      0.237

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     13/100      3.37G     0.7557      1.471      1.277     0.2012        155        832: 100% ━━━━━━━━━━━━ 46/46 5.8it/s 7.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.4it/s 1.9s0.2s
                   all         91       2188      0.417      0.346      0.304      0.246

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     14/100      2.53G     0.7499      1.427      1.258     0.1844        238        832: 100% ━━━━━━━━━━━━ 46/46 5.8it/s 8.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.3it/s 1.9s0.2s
                   all         91       2188      0.408      0.398      0.341      0.272

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     15/100      2.89G     0.7396      1.393      1.265     0.1904        142        832: 100% ━━━━━━━━━━━━ 46/46 5.5it/s 8.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.6it/s 1.8s0.2s
                   all         91       2188      0.304       0.47      0.362      0.285

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     16/100      2.89G     0.7554      1.405      1.277     0.1911        124        832: 100% ━━━━━━━━━━━━ 46/46 5.7it/s 8.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.4it/s 1.9s0.2s
                   all         91       2188      0.319      0.471      0.366       0.29

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     17/100      2.89G     0.7479      1.387      1.248     0.1831        222        832: 100% ━━━━━━━━━━━━ 46/46 5.7it/s 8.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.5it/s 1.8s0.2s
                   all         91       2188      0.338      0.481      0.374      0.295

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     18/100      2.89G     0.7307      1.357      1.247     0.1783        131        832: 100% ━━━━━━━━━━━━ 46/46 5.6it/s 8.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.9it/s 2.0s0.2s
                   all         91       2188       0.35      0.463      0.381        0.3

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     19/100      2.89G     0.7286      1.355      1.248      0.179        186        832: 100% ━━━━━━━━━━━━ 46/46 5.5it/s 8.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.4it/s 1.9s0.2s
                   all         91       2188      0.273       0.53      0.371      0.298

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     20/100      3.28G     0.7172      1.346      1.241     0.1708        404        832: 100% ━━━━━━━━━━━━ 46/46 5.4it/s 8.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.6it/s 1.8s0.2s
                   all         91       2188      0.536      0.449      0.425      0.336

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     21/100      2.25G     0.7142      1.317      1.226     0.1767        145        832: 100% ━━━━━━━━━━━━ 46/46 5.7it/s 8.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.8it/s 1.8s0.2s
                   all         91       2188      0.509      0.505      0.424      0.338

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     22/100      2.61G     0.7256      1.348      1.256     0.1727        236        832: 100% ━━━━━━━━━━━━ 46/46 5.3it/s 8.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.4it/s 1.9s0.2s
                   all         91       2188      0.562        0.5      0.442      0.354

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     23/100      2.99G     0.7179      1.296      1.247     0.1888        406        832: 100% ━━━━━━━━━━━━ 46/46 5.4it/s 8.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.3it/s 1.9s0.2s
                   all         91       2188       0.55      0.531      0.456      0.358

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     24/100      3.43G     0.7211      1.326      1.246     0.1753        182        832: 100% ━━━━━━━━━━━━ 46/46 5.6it/s 8.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.8it/s 1.8s0.2s
                   all         91       2188       0.61      0.493      0.472      0.377

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     25/100      2.61G     0.6945      1.257      1.233     0.1739        131        832: 100% ━━━━━━━━━━━━ 46/46 5.7it/s 8.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.5it/s 1.8s0.2s
                   all         91       2188      0.596      0.541       0.49      0.391

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     26/100      2.97G     0.6899      1.242      1.232     0.1813        115        832: 100% ━━━━━━━━━━━━ 46/46 5.7it/s 8.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.7it/s 1.8s0.2s
                   all         91       2188      0.588      0.506      0.471      0.386

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     27/100      2.97G      0.714      1.288      1.232     0.1617        144        832: 100% ━━━━━━━━━━━━ 46/46 5.7it/s 8.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.8it/s 1.8s0.2s
                   all         91       2188      0.588       0.54      0.491      0.398

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     28/100       3.4G     0.7015      1.271      1.235      0.176        124        832: 100% ━━━━━━━━━━━━ 46/46 5.4it/s 8.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.7it/s 1.8s0.2s
                   all         91       2188      0.612      0.547      0.511       0.41

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     29/100      2.12G     0.7002      1.254      1.226      0.166        355        832: 100% ━━━━━━━━━━━━ 46/46 5.7it/s 8.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.8it/s 1.8s0.1s
                   all         91       2188      0.655      0.519      0.504      0.413

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     30/100      2.48G     0.6981      1.229      1.237     0.1769        412        832: 100% ━━━━━━━━━━━━ 46/46 5.4it/s 8.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.5it/s 1.9s0.2s
                   all         91       2188      0.588      0.555       0.52      0.422

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     31/100      2.48G     0.7106      1.258      1.224     0.1678        217        832: 100% ━━━━━━━━━━━━ 46/46 5.6it/s 8.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.9it/s 1.7s0.2s
                   all         91       2188      0.631      0.529      0.579      0.471

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     32/100      2.88G     0.7103      1.275      1.225     0.1607        143        832: 100% ━━━━━━━━━━━━ 46/46 5.6it/s 8.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.6it/s 1.8s0.2s
                   all         91       2188       0.62      0.521      0.516       0.42

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size

In [15]:
best_pt = r"C:\Users\ROG\runs\obb\runs_obb\obb_debug_832_ep100\weights\best.pt"

In [17]:
from ultralytics import YOLO
import os

best_pt = r"C:\Users\ROG\runs\obb\runs_obb\obb_debug_832_ep100\weights\best.pt"

print("best.pt exists:", os.path.isfile(best_pt))

best_model = YOLO(best_pt)
print("Model loaded successfully")

best.pt exists: True
Model loaded successfully

In [19]:
from pathlib import Path
import os

run_dir = Path(r"C:\Users\ROG\runs\obb\runs_obb\obb_debug_832_ep100")
weights_dir = run_dir / "weights"

print("Run dir exists:", run_dir.exists(), run_dir)
print("Weights dir exists:", weights_dir.exists(), weights_dir)

if weights_dir.exists():
    print("Weights files:", os.listdir(weights_dir))

Run dir exists: True C:\Users\ROG\runs\obb\runs_obb\obb_debug_832_ep100
Weights dir exists: True C:\Users\ROG\runs\obb\runs_obb\obb_debug_832_ep100\weights
Weights files: ['best.pt', 'last.pt']

In [21]:
from ultralytics import YOLO

best_pt = r"C:\Users\ROG\runs\obb\runs_obb\obb_debug_832_ep100\weights\best.pt"
best_model = YOLO(best_pt)

conf_list = [0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.50]

for conf in conf_list:
    best_model.predict(
        source=r"C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test",
        conf=conf,
        save=True,
        save_txt=True,
        project=r"C:\Users\ROG\runs_obb_thresholds",
        name=f"pred_conf_{str(conf).replace('.', '_')}",
        exist_ok=True
    )
    print("Done:", conf)

image 1/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_027934b8-task-936_merged.png: 480x832 27 Interphases, 13 Prophases, 4 Lateprophases, 59.4ms
image 2/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_12a62314-task-918_merged.png: 480x832 32 Interphases, 15 Prophases, 1 Lateprophase, 35.6ms
image 3/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_131eae8f-task-885_merged.png: 480x832 107 Interphases, 16 Prophases, 4 Metaphases, 3 Anaphases, 35.4ms
image 4/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_14d4b2bd-task-958_merged.png: 480x832 27 Interphases, 1 Prophase, 35.6ms
image 5/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_150ac7b3-task-943_merged.png: 480x832 26 Interphases, 2 Prophases, 36.5ms
image 6/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_2ea6ceb2-task-952_merged.png: 480x832 31 Interphases, 5 Prophases, 1 Metaphase, 1 Anaphase, 1 Lateanaphase, 35.7ms
image 7/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_329e44c8-task-840_merged.png: 480x832 39 Interphases, 15 Prophases, 35.6ms
image 8/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_39106d25-task-955_merged.png: 480x832 42 Interphases, 10 Prophases, 5 Lateprophases, 35.6ms
image 9/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_4230b3c7-task-935_merged.png: 480x832 17 Interphases, 1 Prophase, 35.9ms
image 10/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_5b5f7e74-task-893_merged.png: 480x832 167 Interphases, 8 Prophases, 2 Metaphases, 3 Anaphases, 36.0ms
image 11/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_66ae929f-task-960_merged.png: 480x832 26 Interphases, 1 Prophase, 36.0ms
image 12/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_6891949f-task-1021_merged.png: 832x704 14 Interphases, 6 Prophases, 6 Metaphases, 2 Anaphases, 8 Lateanaphases, 53.7ms
image 13/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_87f76e4a-task-913_merged.png: 480x832 12 Interphases, 37.6ms
image 14/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_9f46dcfb-task-1029_merged.png: 480x832 229 Interphases, 37 Prophases, 28 Lateprophases, 6 Metaphases, 35.9ms
image 15/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_a1e23e60-task-925_merged.png: 480x832 21 Interphases, 4 Prophases, 32.7ms
image 16/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_a1fc5d61-task-842_merged.png: 480x832 47 Interphases, 16 Prophases, 1 Lateprophase, 32.6ms
image 17/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_a26de45e-task-892_merged.png: 480x832 207 Interphases, 68 Prophases, 8 Lateprophases, 5 Metaphases, 32.7ms
image 18/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_b53f5c15-task-1026_merged.png: 480x832 34 Interphases, 32 Prophases, 1 Lateprophase, 29.2ms
image 19/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_bde07268-task-884_merged.png: 480x832 79 Interphases, 29 Prophases, 17 Lateprophases, 1 Metaphase, 29.2ms
image 20/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_df44f14d-task-854_merged.png: 480x832 43 Interphases, 19 Prophases, 2 Lateprophases, 29.2ms
image 21/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_eb21b877-task-881_merged.png: 480x832 79 Interphases, 20 Prophases, 1 Lateprophase, 5 Metaphases, 3 Anaphases, 29.3ms
image 22/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_0fdd16e2-Capture_401.bmp: 640x832 33 Interphases, 20 Prophases, 8 Lateprophases, 5 Metaphases, 72.3ms
image 23/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_303baa42-Capture_328.bmp: 640x832 5 Interphases, 2 Prophases, 42.3ms
image 24/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_322560f9-Capture_430.bmp: 640x832 17 Interphases, 39 Prophases, 18 Lateprophases, 2 Metaphases, 42.4ms
image 25/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_40c93c28-Capture_380.bmp: 640x832 32 Interphases, 34 Prophases, 5 Lateprophases, 21.3ms
image 26/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_5c986512-Capture_344.bmp: 640x832 13 Interphases, 16 Prophases, 21.3ms
image 27/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_7012b381-Capture_317.bmp: 640x832 28 Interphases, 42 Prophases, 5 Lateprophases, 4 Metaphases, 4 Anaphases, 21.3ms
image 28/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_7263823d-Capture_397.bmp: 640x832 34 Interphases, 46 Prophases, 8 Lateprophases, 1 Metaphase, 21.3ms
image 29/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_81898f4e-Capture_498.bmp: 640x832 28 Interphases, 16 Prophases, 9 Lateprophases, 5 Metaphases, 1 Lateanaphase, 21.3ms
image 30/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_8228ef6e-Capture_318.bmp: 640x832 33 Interphases, 49 Prophases, 6 Lateprophases, 4 Metaphases, 4 Anaphases, 21.3ms
image 31/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_85d2e370-Capture_384.bmp: 640x832 20 Interphases, 50 Prophases, 15 Lateprophases, 1 Metaphase, 21.3ms
image 32/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_95c8ad16-Capture_497.bmp: 640x832 58 Interphases, 24 Prophases, 9 Lateprophases, 14 Metaphases, 1 Anaphase, 2 Lateanaphases, 21.3ms
image 33/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_9909f173-Capture_419.bmp: 640x832 22 Interphases, 63 Prophases, 10 Lateprophases, 3 Metaphases, 42.8ms
image 34/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_a659789f-Capture_297.bmp: 640x832 23 Interphases, 7 Prophases, 42.7ms
image 35/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_adaaa03f-Capture_463.bmp: 640x832 27 Interphases, 28 Prophases, 4 Lateprophases, 1 Metaphase, 42.7ms
image 36/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_aecee61b-Capture_482.bmp: 640x832 23 Interphases, 42.3ms
image 37/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_b704b520-Capture_376.bmp: 640x832 25 Interphases, 55 Prophases, 7 Lateprophases, 1 Metaphase, 42.1ms
image 38/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_beeb5061-Capture_272.bmp: 640x832 39 Interphases, 32 Prophases, 4 Lateprophases, 2 Metaphases, 5 Anaphases, 1 Lateanaphase, 41.4ms
image 39/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_c280a213-Capture_248.bmp: 640x832 41 Interphases, 10 Prophases, 2 Metaphases, 3 Anaphases, 41.3ms
image 40/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_c8260bd4-Capture_469.bmp: 640x832 31 Interphases, 18 Prophases, 4 Lateprophases, 1 Lateanaphase, 41.3ms
image 41/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_c8ee909a-Capture_431.bmp: 640x832 12 Interphases, 44 Prophases, 21 Lateprophases, 2 Metaphases, 41.3ms
image 42/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_de1d026a-Capture_207.bmp: 640x832 5 Interphases, 5 Prophases, 41.3ms
image 43/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_df063d53-Capture_275.bmp: 640x832 41 Interphases, 14 Prophases, 1 Metaphase, 5 Anaphases, 41.3ms
image 44/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_e541dc92-Capture_250.bmp: 640x832 47 Interphases, 36 Prophases, 8 Lateprophases, 4 Metaphases, 5 Anaphases, 41.3ms
image 45/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_f696428f-Capture_423.bmp: 640x832 30 Interphases, 41 Prophases, 15 Lateprophases, 3 Metaphases, 41.3ms
image 46/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_f8f014d4-Capture_418.bmp: 640x832 33 Interphases, 16 Prophases, 6 Lateprophases, 3 Metaphases, 41.4ms
image 47/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_fd12da3b-Capture_217.bmp: 640x832 8 Interphases, 6 Prophases, 41.3ms
Speed: 6.6ms preprocess, 36.4ms inference, 10.5ms postprocess per image at shape (1, 3, 640, 832)
Results saved to C:\Users\ROG\runs_obb_thresholds\pred_conf_0_1
47 labels saved to C:\Users\ROG\runs_obb_thresholds\pred_conf_0_1\labels
Done: 0.1

image 1/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_027934b8-task-936_merged.png: 480x832 25 Interphases, 12 Prophases, 4 Lateprophases, 30.9ms
image 2/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_12a62314-task-918_merged.png: 480x832 32 Interphases, 15 Prophases, 1 Lateprophase, 30.0ms
image 3/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_131eae8f-task-885_merged.png: 480x832 85 Interphases, 13 Prophases, 3 Metaphases, 3 Anaphases, 29.9ms
image 4/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_14d4b2bd-task-958_merged.png: 480x832 25 Interphases, 1 Prophase, 30.0ms
image 5/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_150ac7b3-task-943_merged.png: 480x832 23 Interphases, 1 Prophase, 31.8ms
image 6/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_2ea6ceb2-task-952_merged.png: 480x832 29 Interphases, 5 Prophases, 1 Metaphase, 1 Anaphase, 1 Lateanaphase, 32.2ms
image 7/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_329e44c8-task-840_merged.png: 480x832 36 Interphases, 13 Prophases, 32.4ms
image 8/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_39106d25-task-955_merged.png: 480x832 38 Interphases, 10 Prophases, 5 Lateprophases, 32.7ms
image 9/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_4230b3c7-task-935_merged.png: 480x832 16 Interphases, 1 Prophase, 33.0ms
image 10/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_5b5f7e74-task-893_merged.png: 480x832 145 Interphases, 7 Prophases, 1 Metaphase, 2 Anaphases, 33.3ms
image 11/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_66ae929f-task-960_merged.png: 480x832 25 Interphases, 1 Prophase, 34.2ms
image 12/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_6891949f-task-1021_merged.png: 832x704 6 Interphases, 3 Prophases, 5 Metaphases, 1 Anaphase, 7 Lateanaphases, 51.6ms
image 13/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_87f76e4a-task-913_merged.png: 480x832 12 Interphases, 32.5ms
image 14/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_9f46dcfb-task-1029_merged.png: 480x832 187 Interphases, 31 Prophases, 23 Lateprophases, 5 Metaphases, 31.3ms
image 15/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_a1e23e60-task-925_merged.png: 480x832 19 Interphases, 4 Prophases, 31.3ms
image 16/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_a1fc5d61-task-842_merged.png: 480x832 45 Interphases, 16 Prophases, 1 Lateprophase, 31.4ms
image 17/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_a26de45e-task-892_merged.png: 480x832 200 Interphases, 66 Prophases, 7 Lateprophases, 5 Metaphases, 31.4ms
image 18/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_b53f5c15-task-1026_merged.png: 480x832 28 Interphases, 30 Prophases, 1 Lateprophase, 15.1ms
image 19/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_bde07268-task-884_merged.png: 480x832 75 Interphases, 27 Prophases, 15 Lateprophases, 1 Metaphase, 15.1ms
image 20/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_df44f14d-task-854_merged.png: 480x832 43 Interphases, 18 Prophases, 2 Lateprophases, 15.1ms
image 21/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_eb21b877-task-881_merged.png: 480x832 60 Interphases, 18 Prophases, 1 Lateprophase, 5 Metaphases, 3 Anaphases, 15.0ms
image 22/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_0fdd16e2-Capture_401.bmp: 640x832 26 Interphases, 12 Prophases, 8 Lateprophases, 4 Metaphases, 44.1ms
image 23/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_303baa42-Capture_328.bmp: 640x832 3 Interphases, 2 Prophases, 43.0ms
image 24/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_322560f9-Capture_430.bmp: 640x832 14 Interphases, 37 Prophases, 18 Lateprophases, 2 Metaphases, 43.1ms
image 25/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_40c93c28-Capture_380.bmp: 640x832 27 Interphases, 27 Prophases, 5 Lateprophases, 41.1ms
image 26/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_5c986512-Capture_344.bmp: 640x832 8 Interphases, 13 Prophases, 41.1ms
image 27/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_7012b381-Capture_317.bmp: 640x832 23 Interphases, 36 Prophases, 5 Lateprophases, 4 Metaphases, 3 Anaphases, 40.9ms
image 28/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_7263823d-Capture_397.bmp: 640x832 21 Interphases, 41 Prophases, 8 Lateprophases, 1 Metaphase, 20.6ms
image 29/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_81898f4e-Capture_498.bmp: 640x832 23 Interphases, 11 Prophases, 9 Lateprophases, 5 Metaphases, 1 Lateanaphase, 20.6ms
image 30/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_8228ef6e-Capture_318.bmp: 640x832 27 Interphases, 43 Prophases, 6 Lateprophases, 4 Metaphases, 3 Anaphases, 20.6ms
image 31/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_85d2e370-Capture_384.bmp: 640x832 14 Interphases, 41 Prophases, 14 Lateprophases, 1 Metaphase, 20.7ms
image 32/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_95c8ad16-Capture_497.bmp: 640x832 42 Interphases, 22 Prophases, 7 Lateprophases, 14 Metaphases, 1 Anaphase, 2 Lateanaphases, 20.6ms
image 33/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_9909f173-Capture_419.bmp: 640x832 14 Interphases, 59 Prophases, 10 Lateprophases, 3 Metaphases, 20.5ms
image 34/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_a659789f-Capture_297.bmp: 640x832 18 Interphases, 7 Prophases, 20.6ms
image 35/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_adaaa03f-Capture_463.bmp: 640x832 17 Interphases, 20 Prophases, 4 Lateprophases, 1 Metaphase, 20.6ms
image 36/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_aecee61b-Capture_482.bmp: 640x832 22 Interphases, 20.6ms
image 37/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_b704b520-Capture_376.bmp: 640x832 15 Interphases, 38 Prophases, 7 Lateprophases, 1 Metaphase, 40.8ms
image 38/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_beeb5061-Capture_272.bmp: 640x832 31 Interphases, 25 Prophases, 4 Lateprophases, 1 Metaphase, 5 Anaphases, 1 Lateanaphase, 41.0ms
image 39/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_c280a213-Capture_248.bmp: 640x832 33 Interphases, 7 Prophases, 2 Metaphases, 3 Anaphases, 41.0ms
image 40/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_c8260bd4-Capture_469.bmp: 640x832 21 Interphases, 15 Prophases, 2 Lateprophases, 1 Lateanaphase, 41.1ms
image 41/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_c8ee909a-Capture_431.bmp: 640x832 11 Interphases, 43 Prophases, 21 Lateprophases, 2 Metaphases, 41.0ms
image 42/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_de1d026a-Capture_207.bmp: 640x832 4 Interphases, 4 Prophases, 41.3ms
image 43/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_df063d53-Capture_275.bmp: 640x832 31 Interphases, 10 Prophases, 1 Metaphase, 5 Anaphases, 41.3ms
image 44/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_e541dc92-Capture_250.bmp: 640x832 36 Interphases, 30 Prophases, 6 Lateprophases, 4 Metaphases, 5 Anaphases, 41.2ms
image 45/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_f696428f-Capture_423.bmp: 640x832 24 Interphases, 31 Prophases, 15 Lateprophases, 3 Metaphases, 41.3ms
image 46/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_f8f014d4-Capture_418.bmp: 640x832 23 Interphases, 11 Prophases, 6 Lateprophases, 3 Metaphases, 41.6ms
image 47/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_fd12da3b-Capture_217.bmp: 640x832 8 Interphases, 4 Prophases, 41.6ms
Speed: 7.1ms preprocess, 32.2ms inference, 8.3ms postprocess per image at shape (1, 3, 640, 832)
Results saved to C:\Users\ROG\runs_obb_thresholds\pred_conf_0_15
47 labels saved to C:\Users\ROG\runs_obb_thresholds\pred_conf_0_15\labels
Done: 0.15

image 1/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_027934b8-task-936_merged.png: 480x832 25 Interphases, 12 Prophases, 4 Lateprophases, 31.4ms
image 2/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_12a62314-task-918_merged.png: 480x832 30 Interphases, 13 Prophases, 1 Lateprophase, 30.4ms
image 3/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_131eae8f-task-885_merged.png: 480x832 70 Interphases, 13 Prophases, 3 Metaphases, 3 Anaphases, 30.9ms
image 4/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_14d4b2bd-task-958_merged.png: 480x832 22 Interphases, 1 Prophase, 32.3ms

In [25]:
from ultralytics import YOLO

model = YOLO("yolov8n-obb.pt")

results = model.train(
    data=yaml_path,
    epochs=100,
    imgsz=832,
    batch=8,
    device=0,
    project=r"C:\Users\ROG\runs_obb",
    name="obb_debug_832_ep100",
    save=True,
    exist_ok=True,
    verbose=True
)

print("Actual save dir:", results.save_dir)

Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=100, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=832, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n-obb.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=obb_debug_832_ep100, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=C:\Users\ROG\runs_obb, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\ROG\runs_obb\obb_debug_832_ep100, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=obb, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=15 with nc=7

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    824344  ultralytics.nn.modules.head.OBB              [7, 1, 16, None, [64, 128, 256]]
YOLOv8n-obb summary: 145 layers, 3,083,880 parameters, 3,083,864 gradients, 8.4 GFLOPs

Transferred 391/397 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.10.0 ms, read: 1316.5137.2 MB/s, size: 3834.8 KB)
train: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\train.cache... 364 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 364/364  0.0s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access  (ping: 0.40.1 ms, read: 952.4161.1 MB/s, size: 4080.1 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000909, momentum=0.9) with parameter groups 63 weight(decay=0.0), 73 weight(decay=0.0005), 72 bias(decay=0.0)
Plotting labels to C:\Users\ROG\runs_obb\obb_debug_832_ep100\labels.jpg...
Image sizes 832 train, 832 val
Using 8 dataloader workers
Logging results to C:\Users\ROG\runs_obb\obb_debug_832_ep100
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      1/100      3.15G      1.445      3.895      1.991     0.3029        123        832: 100% ━━━━━━━━━━━━ 46/46 4.6it/s 10.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.0it/s 2.0s0.2s
                   all         91       2188      0.644        0.1     0.0652       0.05

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      2/100      2.85G      1.022       2.37      1.642     0.2246        279        832: 100% ━━━━━━━━━━━━ 46/46 5.9it/s 7.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.9it/s 1.7s0.1s
                   all         91       2188      0.226      0.181     0.0937     0.0779

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      3/100      3.23G     0.9305      1.999      1.563     0.2096        145        832: 100% ━━━━━━━━━━━━ 46/46 6.2it/s 7.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.4it/s 2.2s0.2s
                   all         91       2188      0.229       0.21      0.115     0.0969

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      4/100      3.24G     0.8962      1.902      1.506     0.2012         94        832: 100% ━━━━━━━━━━━━ 46/46 6.3it/s 7.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.7it/s 2.1s0.2s
                   all         91       2188      0.411      0.239      0.149      0.123

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      5/100      2.98G     0.8785      1.734      1.438     0.2299        188        832: 100% ━━━━━━━━━━━━ 46/46 6.3it/s 7.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.9it/s 2.0s0.2s
                   all         91       2188      0.444      0.221      0.174      0.143

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      6/100      2.98G     0.8583      1.682      1.364     0.2098        140        832: 100% ━━━━━━━━━━━━ 46/46 6.2it/s 7.4s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.6it/s 2.1s0.2s
                   all         91       2188      0.454      0.221      0.189      0.156

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      7/100      2.98G     0.8386      1.649       1.34     0.2102        166        832: 100% ━━━━━━━━━━━━ 46/46 6.1it/s 7.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.0it/s 2.0s0.2s
                   all         91       2188      0.474      0.225       0.22       0.18

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      8/100      2.98G      0.827      1.597      1.324     0.2015        156        832: 100% ━━━━━━━━━━━━ 46/46 6.2it/s 7.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.9it/s 2.0s0.2s
                   all         91       2188      0.313      0.248      0.223      0.183

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      9/100      2.98G     0.8106      1.567      1.309     0.2062        128        832: 100% ━━━━━━━━━━━━ 46/46 6.1it/s 7.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.2it/s 1.9s0.2s
                   all         91       2188      0.529      0.259       0.25      0.203

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     10/100      2.98G     0.7808      1.504        1.3     0.1951        290        832: 100% ━━━━━━━━━━━━ 46/46 6.1it/s 7.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.7it/s 2.1s0.2s
                   all         91       2188      0.346      0.381      0.253      0.207

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     11/100      2.98G     0.7906      1.518      1.284     0.1947        162        832: 100% ━━━━━━━━━━━━ 46/46 6.0it/s 7.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.3it/s 1.9s0.2s
                   all         91       2188      0.344      0.411      0.296      0.239

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     12/100      2.98G     0.7775      1.481      1.285      0.197        140        832: 100% ━━━━━━━━━━━━ 46/46 5.8it/s 7.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.2it/s 1.9s0.2s
                   all         91       2188      0.379      0.365      0.295      0.237

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     13/100       3.5G     0.7557      1.471      1.277     0.2012        155        832: 100% ━━━━━━━━━━━━ 46/46 5.8it/s 7.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.0it/s 2.0s0.2s
                   all         91       2188      0.417      0.346      0.304      0.246

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     14/100       2.6G     0.7499      1.427      1.258     0.1844        238        832: 100% ━━━━━━━━━━━━ 46/46 5.7it/s 8.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.1it/s 2.0s0.2s
                   all         91       2188      0.408      0.398      0.341      0.272

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     15/100      2.97G     0.7396      1.393      1.265     0.1904        142        832: 100% ━━━━━━━━━━━━ 46/46 5.8it/s 7.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.6it/s 1.8s0.2s
                   all         91       2188      0.304       0.47      0.362      0.285

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     16/100      2.97G     0.7554      1.405      1.277     0.1911        124        832: 100% ━━━━━━━━━━━━ 46/46 6.1it/s 7.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.4it/s 1.9s0.2s
                   all         91       2188      0.319      0.471      0.366       0.29

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     17/100      2.97G     0.7479      1.387      1.248     0.1831        222        832: 100% ━━━━━━━━━━━━ 46/46 6.0it/s 7.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.4it/s 1.9s0.2s
                   all         91       2188      0.338      0.481      0.374      0.295

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     18/100      2.97G     0.7307      1.357      1.247     0.1783        131        832: 100% ━━━━━━━━━━━━ 46/46 5.7it/s 8.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.6it/s 1.8s0.2s
                   all         91       2188       0.35      0.463      0.381        0.3

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     19/100      2.97G     0.7286      1.355      1.248      0.179        186        832: 100% ━━━━━━━━━━━━ 46/46 5.8it/s 7.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.1it/s 2.0s0.2s
                   all         91       2188      0.273       0.53      0.371      0.298

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     20/100      3.35G     0.7172      1.346      1.241     0.1708        404        832: 100% ━━━━━━━━━━━━ 46/46 6.0it/s 7.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.7it/s 1.8s0.2s
                   all         91       2188      0.536      0.449      0.425      0.336

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     21/100      2.32G     0.7142      1.317      1.226     0.1767        145        832: 100% ━━━━━━━━━━━━ 46/46 5.9it/s 7.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.9it/s 1.7s0.1s
                   all         91       2188      0.509      0.505      0.424      0.338

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     22/100      2.68G     0.7256      1.348      1.256     0.1727        236        832: 100% ━━━━━━━━━━━━ 46/46 6.0it/s 7.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.7it/s 1.8s0.2s
                   all         91       2188      0.562        0.5      0.442      0.354

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     23/100      3.06G     0.7179      1.296      1.247     0.1888        406        832: 100% ━━━━━━━━━━━━ 46/46 6.0it/s 7.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.9it/s 1.7s0.1s
                   all         91       2188       0.55      0.531      0.456      0.358

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     24/100      3.22G     0.7211      1.326      1.246     0.1753        182        832: 100% ━━━━━━━━━━━━ 46/46 5.8it/s 8.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.9it/s 1.7s0.1s
                   all         91       2188       0.61      0.493      0.472      0.377

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     25/100      2.68G     0.6945      1.257      1.233     0.1739        131        832: 100% ━━━━━━━━━━━━ 46/46 5.8it/s 8.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.5it/s 1.8s0.2s
                   all         91       2188      0.596      0.541       0.49      0.391

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     26/100      3.04G     0.6899      1.242      1.232     0.1813        115        832: 100% ━━━━━━━━━━━━ 46/46 5.8it/s 8.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.8it/s 1.8s0.2s
                   all         91       2188      0.588      0.506      0.471      0.386

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     27/100      2.61G      0.714      1.288      1.232     0.1617        144        832: 100% ━━━━━━━━━━━━ 46/46 5.8it/s 7.9s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.9it/s 1.7s0.1s
                   all         91       2188      0.588       0.54      0.491      0.398

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     28/100      3.35G     0.7015      1.271      1.235      0.176        124        832: 100% ━━━━━━━━━━━━ 46/46 5.7it/s 8.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.7it/s 1.8s0.2s
                   all         91       2188      0.612      0.547      0.511       0.41

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     29/100       2.2G     0.7002      1.254      1.226      0.166        355        832: 100% ━━━━━━━━━━━━ 46/46 5.6it/s 8.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.7it/s 1.8s0.2s
                   all         91       2188      0.655      0.519      0.504      0.413

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     30/100      2.55G     0.6981      1.229      1.237     0.1769        412        832: 100% ━━━━━━━━━━━━ 46/46 5.6it/s 8.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.2it/s 1.9s0.2s
                   all         91       2188      0.588      0.555       0.52      0.422

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     31/100      2.55G     0.7106      1.258      1.224     0.1678        217        832: 100% ━━━━━━━━━━━━ 46/46 5.6it/s 8.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.5it/s 1.8s0.2s
                   all         91       2188      0.631      0.529      0.579      0.471

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     32/100      2.96G     0.7103      1.275      1.225     0.1607        143        832: 100% ━━━━━━━━━━━━ 46/46 5.5it/s 8.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.4it/s 1.9s0.2s
                   all         91       2188       0.62      0.521      0.516       0.42

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size

In [27]:
from ultralytics import YOLO
import os

best_pt = r"C:\Users\ROG\runs\obb\runs_obb\obb_debug_832_ep100\weights\best.pt"
print(os.path.isfile(best_pt))

best_model = YOLO(best_pt)
print("Model loaded successfully")

True
Model loaded successfully

In [29]:
metrics = best_model.val(data=yaml_path, split="val")
print(metrics)

Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
YOLOv8n-obb summary (fused): 82 layers, 3,078,584 parameters, 0 gradients, 8.3 GFLOPs
val: Fast image access  (ping: 0.10.0 ms, read: 2059.8422.8 MB/s, size: 3507.9 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 1.2s/it 7.0s1.0ss
                   all         91       2188      0.801      0.547      0.662      0.553
            Interphase         87       1106       0.74      0.638      0.758      0.679
              Prophase         84        709      0.611      0.553      0.613      0.543
          Lateprophase         47        221      0.716      0.616      0.738      0.621
             Metaphase         42         94      0.933      0.543      0.801      0.596
              Anaphase         19         37      0.771      0.757      0.858      0.725
          Lateanaphase         12         18      0.835      0.722      0.788      0.633
             Telophase          3          3          1          0     0.0807     0.0716
Speed: 5.0ms preprocess, 9.4ms inference, 0.0ms loss, 21.7ms postprocess per image
Results saved to C:\Users\ROG\runs\obb\val8
ultralytics.utils.metrics.OBBMetrics object with attributes:

ap_class_index: array([0, 1, 2, 3, 4, 5, 6])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x0000022C2214DB70>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,    0.025808,    0.012904,           0],
       [          1,           1,           1, ...,    0.010567,   0.0052837,           0],
       [          1,           1,           1, ...,    0.010147,   0.0050736,           0],
       ...,
       [          1,           1,           1, ...,    0.011958,   0.0059791,           0],
       [          1,           1,           1, ...,   0.0081682,   0.0040841,           0],
       [   0.081081,    0.081081,    0.081081, ...,    0.081081,    0.081081,           0]], shape=(7, 1000)), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,

In [31]:
import os
from ultralytics import YOLO

best_paths = [
    r"C:\Users\ROG\runs\obb\runs_obb\obb_debug_832_ep100\weights\best.pt",
]

for best_pt in best_paths:
    if os.path.isfile(best_pt):
        model = YOLO(best_pt)
        metrics = model.val(data=yaml_path, split="val")
        print(best_pt)
        print(metrics)

Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
YOLOv8n-obb summary (fused): 82 layers, 3,078,584 parameters, 0 gradients, 8.3 GFLOPs
val: Fast image access  (ping: 0.00.0 ms, read: 2738.3118.7 MB/s, size: 3234.8 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 1.2s/it 6.9s1.1ss
                   all         91       2188      0.801      0.547      0.662      0.553
            Interphase         87       1106       0.74      0.638      0.758      0.679
              Prophase         84        709      0.611      0.553      0.613      0.543
          Lateprophase         47        221      0.716      0.616      0.738      0.621
             Metaphase         42         94      0.933      0.543      0.801      0.596
              Anaphase         19         37      0.771      0.757      0.858      0.725
          Lateanaphase         12         18      0.835      0.722      0.788      0.633
             Telophase          3          3          1          0     0.0807     0.0716
Speed: 4.8ms preprocess, 8.3ms inference, 0.0ms loss, 20.2ms postprocess per image
Results saved to C:\Users\ROG\runs\obb\val9
C:\Users\ROG\runs\obb\runs_obb\obb_debug_832_ep100\weights\best.pt
ultralytics.utils.metrics.OBBMetrics object with attributes:

ap_class_index: array([0, 1, 2, 3, 4, 5, 6])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x0000022C21F4CA30>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,    0.025808,    0.012904,           0],
       [          1,           1,           1, ...,    0.010567,   0.0052837,           0],
       [          1,           1,           1, ...,    0.010147,   0.0050736,           0],
       ...,
       [          1,           1,           1, ...,    0.011958,   0.0059791,           0],
       [          1,           1,           1, ...,   0.0081682,   0.0040841,           0],
       [   0.081081,    0.081081,    0.081081, ...,    0.081081,    0.081081,           0]], shape=(7, 1000)), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,

In [33]:
import os
import json
import pandas as pd
from ultralytics import YOLO

# Dataset YAML
yaml_path = r"C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\data.yaml"

# Best model from your successful run
best_pt = r"C:\Users\ROG\runs\obb\runs_obb\obb_debug_832_ep100\weights\best.pt"

# Test images
test_source = r"C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test"

print("yaml exists:", os.path.isfile(yaml_path))
print("best.pt exists:", os.path.isfile(best_pt))
print("test folder exists:", os.path.isdir(test_source))

yaml exists: True
best.pt exists: True
test folder exists: True

In [35]:
best_model = YOLO(best_pt)
print("Model loaded successfully")

Model loaded successfully

In [37]:
metrics = best_model.val(data=yaml_path, split="val")
print(metrics)

Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
YOLOv8n-obb summary (fused): 82 layers, 3,078,584 parameters, 0 gradients, 8.3 GFLOPs
val: Fast image access  (ping: 0.10.0 ms, read: 2273.7171.1 MB/s, size: 3577.7 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 1.3s/it 8.1s1.0ss
                   all         91       2188      0.801      0.547      0.662      0.553
            Interphase         87       1106       0.74      0.638      0.758      0.679
              Prophase         84        709      0.611      0.553      0.613      0.543
          Lateprophase         47        221      0.716      0.616      0.738      0.621
             Metaphase         42         94      0.933      0.543      0.801      0.596
              Anaphase         19         37      0.771      0.757      0.858      0.725
          Lateanaphase         12         18      0.835      0.722      0.788      0.633
             Telophase          3          3          1          0     0.0807     0.0716
Speed: 5.2ms preprocess, 7.9ms inference, 0.0ms loss, 18.7ms postprocess per image
Results saved to C:\Users\ROG\runs\obb\val10
ultralytics.utils.metrics.OBBMetrics object with attributes:

ap_class_index: array([0, 1, 2, 3, 4, 5, 6])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x0000022C222B6470>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,    0.025808,    0.012904,           0],
       [          1,           1,           1, ...,    0.010567,   0.0052837,           0],
       [          1,           1,           1, ...,    0.010147,   0.0050736,           0],
       ...,
       [          1,           1,           1, ...,    0.011958,   0.0059791,           0],
       [          1,           1,           1, ...,   0.0081682,   0.0040841,           0],
       [   0.081081,    0.081081,    0.081081, ...,    0.081081,    0.081081,           0]], shape=(7, 1000)), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,

In [39]:
conf_list = [0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.50]
rows = []

for conf in conf_list:
    m = best_model.val(
        data=yaml_path,
        split="val",
        conf=conf,
        imgsz=832,
        plots=False,
        save_json=False,
        verbose=False
    )

    row = {
        "conf": conf,
        "precision_B": getattr(m.box, "mp", None) if hasattr(m, "box") else None,
        "recall_B": getattr(m.box, "mr", None) if hasattr(m, "box") else None,
        "map50_B": getattr(m.box, "map50", None) if hasattr(m, "box") else None,
        "map50_95_B": getattr(m.box, "map", None) if hasattr(m, "box") else None,
    }

    if row["precision_B"] is not None and row["recall_B"] is not None:
        p = row["precision_B"]
        r = row["recall_B"]
        row["f1_B"] = 2 * p * r / (p + r + 1e-9)
    else:
        row["f1_B"] = None

    rows.append(row)
    print(row)

threshold_df = pd.DataFrame(rows)
threshold_df

Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 1211.4512.0 MB/s, size: 3785.5 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.3it/s 2.7s0.3ss
                   all         91       2188      0.801      0.547       0.65      0.545
Speed: 1.7ms preprocess, 7.1ms inference, 0.0ms loss, 4.9ms postprocess per image
{'conf': 0.05, 'precision_B': np.float64(0.80093557338269), 'recall_B': np.float64(0.5469009321936743), 'map50_B': np.float64(0.650316223444653), 'map50_95_B': np.float64(0.5450401068314052), 'f1_B': np.float64(0.6499785538866476)}
Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 2062.1278.4 MB/s, size: 3807.0 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.4it/s 2.5s0.3ss
                   all         91       2188      0.801      0.547      0.644      0.542
Speed: 1.7ms preprocess, 5.3ms inference, 0.0ms loss, 4.9ms postprocess per image
{'conf': 0.1, 'precision_B': np.float64(0.80093557338269), 'recall_B': np.float64(0.5469009321936743), 'map50_B': np.float64(0.6440209958019789), 'map50_95_B': np.float64(0.5415735060156124), 'f1_B': np.float64(0.6499785538866476)}
Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
val: Fast image access  (ping: 0.20.2 ms, read: 1918.895.1 MB/s, size: 3847.0 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.3it/s 2.7s0.3ss
                   all         91       2188      0.801      0.547      0.642      0.542
Speed: 1.8ms preprocess, 6.2ms inference, 0.0ms loss, 4.5ms postprocess per image
{'conf': 0.15, 'precision_B': np.float64(0.80093557338269), 'recall_B': np.float64(0.5469009321936743), 'map50_B': np.float64(0.642120021862123), 'map50_95_B': np.float64(0.5416670853939083), 'f1_B': np.float64(0.6499785538866476)}
Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 2101.6259.0 MB/s, size: 3563.8 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.4it/s 2.5s0.3ss
                   all         91       2188      0.801      0.547      0.638      0.539
Speed: 1.7ms preprocess, 5.0ms inference, 0.0ms loss, 4.8ms postprocess per image
{'conf': 0.2, 'precision_B': np.float64(0.80093557338269), 'recall_B': np.float64(0.5469009321936743), 'map50_B': np.float64(0.6379181668007747), 'map50_95_B': np.float64(0.5391986011567568), 'f1_B': np.float64(0.6499785538866476)}
Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 1908.9205.5 MB/s, size: 3840.3 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.3it/s 2.6s0.3ss
                   all         91       2188      0.658      0.547      0.635      0.538
Speed: 1.6ms preprocess, 6.4ms inference, 0.0ms loss, 4.6ms postprocess per image
{'conf': 0.25, 'precision_B': np.float64(0.6580784305255472), 'recall_B': np.float64(0.5469009321936743), 'map50_B': np.float64(0.6346022048692053), 'map50_95_B': np.float64(0.5376249007254738), 'f1_B': np.float64(0.597360781350003)}
Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 1922.6163.3 MB/s, size: 3531.7 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.3it/s 2.6s0.3ss
                   all         91       2188      0.658      0.547      0.631      0.535
Speed: 1.7ms preprocess, 7.1ms inference, 0.0ms loss, 4.6ms postprocess per image
{'conf': 0.3, 'precision_B': np.float64(0.6580784305255472), 'recall_B': np.float64(0.5469009321936743), 'map50_B': np.float64(0.6305912279109608), 'map50_95_B': np.float64(0.5350200171772028), 'f1_B': np.float64(0.597360781350003)}
Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
val: Fast image access  (ping: 0.00.0 ms, read: 2263.1381.2 MB/s, size: 3448.8 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.3it/s 2.6s0.3ss
                   all         91       2188      0.658      0.547      0.628      0.534
Speed: 1.7ms preprocess, 7.1ms inference, 0.0ms loss, 4.5ms postprocess per image
{'conf': 0.35, 'precision_B': np.float64(0.6580784305255472), 'recall_B': np.float64(0.5469009321936743), 'map50_B': np.float64(0.6275824750026212), 'map50_95_B': np.float64(0.534407354075778), 'f1_B': np.float64(0.597360781350003)}
Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 2061.9379.9 MB/s, size: 3850.8 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 1.8it/s 3.4s0.3ss
                   all         91       2188      0.658      0.547      0.624      0.532
Speed: 1.6ms preprocess, 6.7ms inference, 0.0ms loss, 4.2ms postprocess per image
{'conf': 0.4, 'precision_B': np.float64(0.6580784305255472), 'recall_B': np.float64(0.5469009321936743), 'map50_B': np.float64(0.6244060723650782), 'map50_95_B': np.float64(0.5316376884939193), 'f1_B': np.float64(0.597360781350003)}
Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 1881.3363.2 MB/s, size: 3673.3 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.3it/s 2.6s0.3ss
                   all         91       2188      0.666      0.547      0.622      0.531
Speed: 1.7ms preprocess, 6.0ms inference, 0.0ms loss, 4.8ms postprocess per image
{'conf': 0.5, 'precision_B': np.float64(0.6662434484510479), 'recall_B': np.float64(0.5468777899118465), 'map50_B': np.float64(0.6216439460591529), 'map50_95_B': np.float64(0.5307849177908619), 'f1_B': np.float64(0.6006880974625539)}

   conf  precision_B  recall_B   map50_B  map50_95_B      f1_B
0  0.05     0.800936  0.546901  0.650316    0.545040  0.649979
1  0.10     0.800936  0.546901  0.644021    0.541574  0.649979
2  0.15     0.800936  0.546901  0.642120    0.541667  0.649979
3  0.20     0.800936  0.546901  0.637918    0.539199  0.649979
4  0.25     0.658078  0.546901  0.634602    0.537625  0.597361
5  0.30     0.658078  0.546901  0.630591    0.535020  0.597361
6  0.35     0.658078  0.546901  0.627582    0.534407  0.597361
7  0.40     0.658078  0.546901  0.624406    0.531638  0.597361
8  0.50     0.666243  0.546878  0.621644    0.530785  0.600688

In [41]:
threshold_df = threshold_df.sort_values(by="f1_B", ascending=False)
best_conf = float(threshold_df.iloc[0]["conf"])
print("Best threshold by F1:", best_conf)
threshold_df.head(10)

Best threshold by F1: 0.05

   conf  precision_B  recall_B   map50_B  map50_95_B      f1_B
0  0.05     0.800936  0.546901  0.650316    0.545040  0.649979
1  0.10     0.800936  0.546901  0.644021    0.541574  0.649979
2  0.15     0.800936  0.546901  0.642120    0.541667  0.649979
3  0.20     0.800936  0.546901  0.637918    0.539199  0.649979
8  0.50     0.666243  0.546878  0.621644    0.530785  0.600688
4  0.25     0.658078  0.546901  0.634602    0.537625  0.597361
5  0.30     0.658078  0.546901  0.630591    0.535020  0.597361
6  0.35     0.658078  0.546901  0.627582    0.534407  0.597361
7  0.40     0.658078  0.546901  0.624406    0.531638  0.597361

In [43]:
pred_results = best_model.predict(
    source=test_source,
    conf=best_conf,
    imgsz=832,
    save=True,
    save_txt=True,
    project=r"C:\Users\ROG\runs_obb_thresholds",
    name=f"best_conf_{str(best_conf).replace('.', '_')}",
    exist_ok=True
)

print("Saved thresholded predictions.")

image 1/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_027934b8-task-936_merged.png: 480x832 29 Interphases, 14 Prophases, 4 Lateprophases, 44.0ms
image 2/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_12a62314-task-918_merged.png: 480x832 35 Interphases, 18 Prophases, 1 Lateprophase, 36.3ms
image 3/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_131eae8f-task-885_merged.png: 480x832 135 Interphases, 19 Prophases, 4 Metaphases, 3 Anaphases, 33.2ms
image 4/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_14d4b2bd-task-958_merged.png: 480x832 30 Interphases, 1 Prophase, 31.3ms
image 5/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_150ac7b3-task-943_merged.png: 480x832 28 Interphases, 2 Prophases, 31.2ms
image 6/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_2ea6ceb2-task-952_merged.png: 480x832 37 Interphases, 6 Prophases, 2 Metaphases, 1 Anaphase, 1 Lateanaphase, 31.3ms
image 7/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_329e44c8-task-840_merged.png: 480x832 43 Interphases, 17 Prophases, 31.3ms
image 8/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_39106d25-task-955_merged.png: 480x832 45 Interphases, 12 Prophases, 6 Lateprophases, 31.4ms
image 9/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_4230b3c7-task-935_merged.png: 480x832 21 Interphases, 1 Prophase, 31.3ms
image 10/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_5b5f7e74-task-893_merged.png: 480x832 200 Interphases, 8 Prophases, 3 Metaphases, 5 Anaphases, 34.7ms
image 11/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_66ae929f-task-960_merged.png: 480x832 30 Interphases, 1 Prophase, 30.8ms
image 12/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_6891949f-task-1021_merged.png: 832x704 21 Interphases, 6 Prophases, 10 Metaphases, 3 Anaphases, 8 Lateanaphases, 53.6ms
image 13/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_87f76e4a-task-913_merged.png: 480x832 13 Interphases, 36.7ms
image 14/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_9f46dcfb-task-1029_merged.png: 480x832 229 Interphases, 37 Prophases, 28 Lateprophases, 6 Metaphases, 35.7ms
image 15/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_a1e23e60-task-925_merged.png: 480x832 22 Interphases, 5 Prophases, 33.9ms
image 16/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_a1fc5d61-task-842_merged.png: 480x832 50 Interphases, 16 Prophases, 1 Lateprophase, 34.0ms
image 17/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_a26de45e-task-892_merged.png: 480x832 214 Interphases, 72 Prophases, 9 Lateprophases, 5 Metaphases, 33.9ms
image 18/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_b53f5c15-task-1026_merged.png: 480x832 38 Interphases, 34 Prophases, 1 Lateprophase, 12.1ms
image 19/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_bde07268-task-884_merged.png: 480x832 86 Interphases, 36 Prophases, 18 Lateprophases, 1 Metaphase, 14.9ms
image 20/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_df44f14d-task-854_merged.png: 480x832 49 Interphases, 19 Prophases, 2 Lateprophases, 5.6ms
image 21/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\A_eb21b877-task-881_merged.png: 480x832 114 Interphases, 24 Prophases, 2 Lateprophases, 7 Metaphases, 3 Anaphases, 8.1ms
image 22/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_0fdd16e2-Capture_401.bmp: 640x832 48 Interphases, 26 Prophases, 10 Lateprophases, 5 Metaphases, 18.9ms
image 23/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_303baa42-Capture_328.bmp: 640x832 8 Interphases, 3 Prophases, 19.7ms
image 24/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_322560f9-Capture_430.bmp: 640x832 27 Interphases, 45 Prophases, 21 Lateprophases, 2 Metaphases, 19.6ms
image 25/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_40c93c28-Capture_380.bmp: 640x832 61 Interphases, 45 Prophases, 6 Lateprophases, 20.0ms
image 26/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_5c986512-Capture_344.bmp: 640x832 21 Interphases, 26 Prophases, 1 Lateprophase, 20.3ms
image 27/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_7012b381-Capture_317.bmp: 640x832 32 Interphases, 49 Prophases, 6 Lateprophases, 4 Metaphases, 4 Anaphases, 20.7ms
image 28/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_7263823d-Capture_397.bmp: 640x832 55 Interphases, 59 Prophases, 8 Lateprophases, 1 Metaphase, 20.9ms
image 29/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_81898f4e-Capture_498.bmp: 640x832 40 Interphases, 21 Prophases, 10 Lateprophases, 5 Metaphases, 1 Lateanaphase, 21.6ms
image 30/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_8228ef6e-Capture_318.bmp: 640x832 40 Interphases, 60 Prophases, 7 Lateprophases, 4 Metaphases, 5 Anaphases, 21.9ms
image 31/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_85d2e370-Capture_384.bmp: 640x832 40 Interphases, 67 Prophases, 18 Lateprophases, 2 Metaphases, 41.8ms
image 32/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_95c8ad16-Capture_497.bmp: 640x832 93 Interphases, 40 Prophases, 12 Lateprophases, 16 Metaphases, 1 Anaphase, 2 Lateanaphases, 41.1ms
image 33/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_9909f173-Capture_419.bmp: 640x832 30 Interphases, 70 Prophases, 11 Lateprophases, 3 Metaphases, 41.1ms
image 34/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_a659789f-Capture_297.bmp: 640x832 28 Interphases, 15 Prophases, 20.9ms
image 35/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_adaaa03f-Capture_463.bmp: 640x832 37 Interphases, 42 Prophases, 4 Lateprophases, 1 Metaphase, 20.9ms
image 36/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_aecee61b-Capture_482.bmp: 640x832 25 Interphases, 21.0ms
image 37/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_b704b520-Capture_376.bmp: 640x832 42 Interphases, 68 Prophases, 10 Lateprophases, 2 Metaphases, 20.9ms
image 38/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_beeb5061-Capture_272.bmp: 640x832 54 Interphases, 50 Prophases, 4 Lateprophases, 2 Metaphases, 6 Anaphases, 1 Lateanaphase, 20.9ms
image 39/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_c280a213-Capture_248.bmp: 640x832 65 Interphases, 19 Prophases, 1 Lateprophase, 2 Metaphases, 3 Anaphases, 20.9ms
image 40/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_c8260bd4-Capture_469.bmp: 640x832 38 Interphases, 24 Prophases, 4 Lateprophases, 2 Anaphases, 2 Lateanaphases, 21.1ms
image 41/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_c8ee909a-Capture_431.bmp: 640x832 18 Interphases, 49 Prophases, 21 Lateprophases, 3 Metaphases, 41.8ms
image 42/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_de1d026a-Capture_207.bmp: 640x832 5 Interphases, 7 Prophases, 41.5ms
image 43/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_df063d53-Capture_275.bmp: 640x832 51 Interphases, 21 Prophases, 3 Lateprophases, 1 Metaphase, 5 Anaphases, 41.3ms
image 44/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_e541dc92-Capture_250.bmp: 640x832 59 Interphases, 56 Prophases, 11 Lateprophases, 5 Metaphases, 6 Anaphases, 20.3ms
image 45/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_f696428f-Capture_423.bmp: 640x832 45 Interphases, 51 Prophases, 17 Lateprophases, 3 Metaphases, 20.5ms
image 46/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_f8f014d4-Capture_418.bmp: 640x832 41 Interphases, 26 Prophases, 6 Lateprophases, 3 Metaphases, 20.3ms
image 47/47 C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\images\test\B_fd12da3b-Capture_217.bmp: 640x832 11 Interphases, 8 Prophases, 20.5ms
Speed: 5.5ms preprocess, 27.6ms inference, 13.6ms postprocess per image at shape (1, 3, 640, 832)
Results saved to C:\Users\ROG\runs_obb_thresholds\best_conf_0_05
47 labels saved to C:\Users\ROG\runs_obb_thresholds\best_conf_0_05\labels
Saved thresholded predictions.

In [45]:
model_s = YOLO("yolov8s-obb.pt")

results_s = model_s.train(
    data=yaml_path,
    epochs=150,
    imgsz=832,
    batch=8,
    device=0,
    project=r"C:\Users\ROG\runs_obb",
    name="obb_s_832_ep150",
    save=True,
    exist_ok=True,
    verbose=True
)

print("Actual save dir:", results_s.save_dir)

Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=150, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=832, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8s-obb.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=obb_s_832_ep150, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=C:\Users\ROG\runs_obb, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\ROG\runs_obb\obb_s_832_ep150, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=obb, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=15 with nc=7

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2404936  ultralytics.nn.modules.head.OBB              [7, 1, 16, None, [128, 256, 512]]
YOLOv8s-obb summary: 145 layers, 11,424,488 parameters, 11,424,472 gradients, 29.6 GFLOPs

Transferred 391/397 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.00.0 ms, read: 713.8161.1 MB/s, size: 3834.8 KB)
train: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\train.cache... 364 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 364/364  0.0s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access  (ping: 0.10.0 ms, read: 1406.5136.3 MB/s, size: 4080.1 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000909, momentum=0.9) with parameter groups 63 weight(decay=0.0), 73 weight(decay=0.0005), 72 bias(decay=0.0)
Plotting labels to C:\Users\ROG\runs_obb\obb_s_832_ep150\labels.jpg...
Image sizes 832 train, 832 val
Using 8 dataloader workers
Logging results to C:\Users\ROG\runs_obb\obb_s_832_ep150
Starting training for 150 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      1/150      4.25G       1.31      3.336      2.017      0.264        123        832: 100% ━━━━━━━━━━━━ 46/46 3.6it/s 12.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 3.8it/s 3.1s0.2s
                   all         91       2188      0.487      0.191     0.0689     0.0565

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      2/150      3.96G     0.9227       1.99       1.63     0.1978        279        832: 100% ━━━━━━━━━━━━ 46/46 4.4it/s 10.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 3.8it/s 3.2s0.3s
                   all         91       2188      0.569      0.234      0.158      0.131

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      3/150      3.94G     0.8437      1.727      1.582     0.1908        145        832: 100% ━━━━━━━━━━━━ 46/46 3.9it/s 11.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 4.4it/s 2.7s0.2s
                   all         91       2188      0.465      0.201      0.181      0.146

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      4/150      3.53G     0.8375      1.678      1.531     0.1827         94        832: 100% ━━━━━━━━━━━━ 46/46 4.3it/s 10.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.9it/s 2.0s0.2s
                   all         91       2188      0.325       0.28      0.213      0.172

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      5/150      4.53G     0.8191      1.579      1.449     0.2012        188        832: 100% ━━━━━━━━━━━━ 46/46 4.3it/s 10.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.8it/s 2.1s0.2s
                   all         91       2188      0.331      0.254      0.224      0.179

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      6/150      3.82G     0.8037      1.549      1.367     0.1884        140        832: 100% ━━━━━━━━━━━━ 46/46 4.2it/s 10.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.1it/s 2.0s0.2s
                   all         91       2188       0.34      0.327      0.243      0.201

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      7/150      4.15G     0.7837      1.504      1.342     0.1893        166        832: 100% ━━━━━━━━━━━━ 46/46 4.0it/s 11.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 3.3it/s 3.6s0.2s
                   all         91       2188      0.224      0.353       0.28       0.23

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      8/150      3.74G     0.7681      1.457      1.308     0.1809        156        832: 100% ━━━━━━━━━━━━ 46/46 4.0it/s 11.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.1it/s 2.0s0.2s
                   all         91       2188      0.425      0.331      0.311      0.253

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
      9/150      4.03G     0.7565      1.418      1.299     0.1806        128        832: 100% ━━━━━━━━━━━━ 46/46 4.0it/s 11.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.9it/s 2.0s0.2s
                   all         91       2188      0.449      0.373      0.354      0.285

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     10/150         4G     0.7298       1.36      1.281     0.1813        290        832: 100% ━━━━━━━━━━━━ 46/46 4.0it/s 11.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.8it/s 2.1s0.2s
                   all         91       2188      0.419      0.445      0.411      0.328

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     11/150       4.1G     0.7368       1.38      1.274     0.1798        162        832: 100% ━━━━━━━━━━━━ 46/46 3.9it/s 11.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.5it/s 2.2s0.2s
                   all         91       2188      0.423      0.505      0.468      0.375

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     12/150      3.55G     0.7314      1.346      1.284     0.1804        140        832: 100% ━━━━━━━━━━━━ 46/46 3.9it/s 11.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.0it/s 2.0s0.2s
                   all         91       2188      0.599      0.519        0.5      0.402

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     13/150      3.94G     0.7125      1.321      1.267     0.1836        155        832: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.3it/s 1.9s0.2s
                   all         91       2188      0.609       0.54      0.504      0.403

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     14/150      3.71G     0.7096      1.273       1.25     0.1681        238        832: 100% ━━━━━━━━━━━━ 46/46 3.9it/s 11.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.8it/s 2.1s0.2s
                   all         91       2188       0.61      0.569      0.544      0.442

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     15/150      3.71G     0.6945      1.252      1.258     0.1744        142        832: 100% ━━━━━━━━━━━━ 46/46 3.9it/s 11.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.8it/s 2.1s0.2s
                   all         91       2188      0.633       0.52      0.524      0.429

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     16/150       4.2G     0.7142       1.27      1.262     0.1742        124        832: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.8it/s 2.1s0.2s
                   all         91       2188      0.602      0.566      0.544      0.445

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     17/150      3.98G     0.7009      1.238      1.233     0.1668        222        832: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.0it/s 2.0s0.2s
                   all         91       2188      0.617       0.58      0.557      0.461

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     18/150      4.24G     0.6835      1.211       1.23     0.1583        131        832: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.3it/s 1.9s0.2s
                   all         91       2188      0.639      0.567      0.568      0.465

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     19/150      4.04G     0.6767      1.204      1.232      0.161        186        832: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.2it/s 1.9s0.2s
                   all         91       2188      0.641      0.571      0.583      0.479

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     20/150      3.75G      0.669        1.2      1.222     0.1546        404        832: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.4it/s 1.9s0.2s
                   all         91       2188      0.676      0.537      0.578      0.472

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     21/150      3.73G     0.6643      1.174      1.214     0.1616        145        832: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.1it/s 2.0s0.2s
                   all         91       2188      0.569      0.633      0.583      0.479

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     22/150      3.71G     0.6776      1.195      1.244     0.1579        236        832: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.5it/s 2.2s0.2s
                   all         91       2188      0.623       0.59       0.58      0.474

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     23/150      4.06G     0.6721      1.169      1.232     0.1717        406        832: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.9it/s 2.0s0.2s
                   all         91       2188      0.662      0.609      0.624      0.515

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     24/150      4.51G      0.679      1.201       1.23     0.1558        182        832: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.4it/s 1.9s0.2s
                   all         91       2188      0.661      0.574      0.609      0.509

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     25/150      4.03G     0.6525      1.133      1.215     0.1564        131        832: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.2it/s 1.9s0.2s
                   all         91       2188      0.461      0.703      0.609      0.504

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     26/150      4.02G      0.653      1.134      1.222     0.1581        115        832: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.4it/s 1.9s0.2s
                   all         91       2188      0.619      0.597      0.592      0.493

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     27/150      3.91G     0.6683      1.171      1.219     0.1402        144        832: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.2it/s 1.9s0.2s
                   all         91       2188      0.662      0.627      0.616      0.511

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     28/150       4.7G     0.6573      1.161      1.218     0.1551        124        832: 100% ━━━━━━━━━━━━ 46/46 3.6it/s 12.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.3it/s 1.9s0.2s
                   all         91       2188      0.682      0.546      0.611      0.504

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     29/150      3.54G     0.6526      1.128      1.201     0.1475        355        832: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.3it/s 1.9s0.2s
                   all         91       2188      0.701      0.564      0.613      0.509

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     30/150      4.59G      0.652      1.103      1.215     0.1545        412        832: 100% ━━━━━━━━━━━━ 46/46 3.6it/s 12.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.3it/s 1.9s0.2s
                   all         91       2188      0.656      0.652      0.628      0.526

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     31/150      3.95G     0.6617      1.135      1.204     0.1505        217        832: 100% ━━━━━━━━━━━━ 46/46 3.6it/s 12.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 5.9it/s 2.0s0.2s
                   all         91       2188      0.673      0.618      0.631      0.526

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size
     32/150      3.94G     0.6635      1.146      1.204     0.1445        143        832: 100% ━━━━━━━━━━━━ 46/46 3.6it/s 12.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 6.3it/s 1.9s0.2s
                   all         91       2188       0.75      0.551       0.65      0.537

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss angle_loss  Instances       Size

In [47]:
best_pt_s = os.path.join(str(results_s.save_dir), "weights", "best.pt")
print("best_pt_s exists:", os.path.isfile(best_pt_s))

best_model_s = YOLO(best_pt_s)
metrics_s = best_model_s.val(data=yaml_path, split="val")
print(metrics_s)

best_pt_s exists: True
Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
YOLOv8s-obb summary (fused): 82 layers, 11,414,280 parameters, 0 gradients, 29.4 GFLOPs
val: Fast image access  (ping: 0.10.0 ms, read: 2301.6580.7 MB/s, size: 3507.9 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 1.1s/it 6.4s0.8ss
                   all         91       2188      0.758       0.79      0.848      0.731
            Interphase         87       1106      0.772      0.741      0.815       0.74
              Prophase         84        709      0.628      0.742       0.73      0.657
          Lateprophase         47        221      0.681      0.783      0.792      0.695
             Metaphase         42         94        0.8      0.819      0.861      0.681
              Anaphase         19         37      0.756      0.838      0.899      0.794
          Lateanaphase         12         18      0.672      0.722      0.845      0.696
             Telophase          3          3          1      0.882      0.995      0.853
Speed: 4.7ms preprocess, 10.9ms inference, 0.0ms loss, 15.3ms postprocess per image
Results saved to C:\Users\ROG\runs\obb\val20
ultralytics.utils.metrics.OBBMetrics object with attributes:

ap_class_index: array([0, 1, 2, 3, 4, 5, 6])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x0000022C248E3EE0>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,    0.013914,   0.0069568,           0],
       [          1,           1,           1, ...,   0.0065274,   0.0032637,           0],
       [          1,           1,           1, ...,   0.0092507,   0.0046254,           0],
       ...,
       [          1,           1,           1, ...,    0.024691,    0.012346,           0],
       [          1,           1,           1, ...,        0.45,        0.45,           0],
       [          1,           1,           1, ...,           1,           1,           0]], shape=(7, 1000)), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,

In [49]:
conf_list = [0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.50]
rows_s = []

for conf in conf_list:
    m = best_model_s.val(
        data=yaml_path,
        split="val",
        conf=conf,
        imgsz=832,
        plots=False,
        save_json=False,
        verbose=False
    )

    row = {
        "conf": conf,
        "precision_B": getattr(m.box, "mp", None) if hasattr(m, "box") else None,
        "recall_B": getattr(m.box, "mr", None) if hasattr(m, "box") else None,
        "map50_B": getattr(m.box, "map50", None) if hasattr(m, "box") else None,
        "map50_95_B": getattr(m.box, "map", None) if hasattr(m, "box") else None,
    }

    if row["precision_B"] is not None and row["recall_B"] is not None:
        p = row["precision_B"]
        r = row["recall_B"]
        row["f1_B"] = 2 * p * r / (p + r + 1e-9)
    else:
        row["f1_B"] = None

    rows_s.append(row)

threshold_df_s = pd.DataFrame(rows_s).sort_values(by="f1_B", ascending=False)
threshold_df_s.head(10)

Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 1210.6686.7 MB/s, size: 3234.8 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.1it/s 2.9s0.4ss
                   all         91       2188      0.758       0.79      0.847      0.733
Speed: 2.6ms preprocess, 9.1ms inference, 0.0ms loss, 4.6ms postprocess per image
Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 1765.3138.7 MB/s, size: 3577.7 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.3it/s 2.6s0.4ss
                   all         91       2188      0.758       0.79      0.838      0.728
Speed: 1.4ms preprocess, 7.2ms inference, 0.0ms loss, 4.9ms postprocess per image
Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 1910.5179.6 MB/s, size: 3785.5 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.2it/s 2.8s0.4ss
                   all         91       2188      0.758       0.79      0.835      0.728
Speed: 1.7ms preprocess, 9.7ms inference, 0.0ms loss, 4.6ms postprocess per image
Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 1983.6463.4 MB/s, size: 3807.0 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.2it/s 2.8s0.4ss
                   all         91       2188      0.758       0.79      0.836      0.729
Speed: 1.7ms preprocess, 9.4ms inference, 0.0ms loss, 4.6ms postprocess per image
Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 1707.7194.5 MB/s, size: 3847.0 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.3it/s 2.6s0.4ss
                   all         91       2188      0.758       0.79      0.836       0.73
Speed: 1.4ms preprocess, 7.3ms inference, 0.0ms loss, 4.9ms postprocess per image
Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 2027.8159.4 MB/s, size: 3563.8 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.1it/s 2.8s0.4ss
                   all         91       2188      0.758       0.79      0.833      0.729
Speed: 1.7ms preprocess, 10.2ms inference, 0.0ms loss, 4.6ms postprocess per image
Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 2159.8450.6 MB/s, size: 3840.3 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.1it/s 2.8s0.4ss
                   all         91       2188      0.758       0.79      0.828      0.726
Speed: 1.7ms preprocess, 10.1ms inference, 0.0ms loss, 4.6ms postprocess per image
Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 1911.0164.6 MB/s, size: 3531.7 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.3it/s 2.6s0.4ss
                   all         91       2188       0.79      0.733      0.804      0.701
Speed: 1.5ms preprocess, 7.2ms inference, 0.0ms loss, 4.9ms postprocess per image
Ultralytics 8.4.21  Python-3.10.19 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 1855.3210.5 MB/s, size: 3448.8 KB)
val: Scanning C:\Users\ROG\Desktop\Datasets_with_annotation_object_detection\Merged_dataset\labels\val.cache... 91 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 91/91  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.1it/s 2.8s0.4ss
                   all         91       2188       0.79      0.739      0.799      0.698
Speed: 1.6ms preprocess, 10.1ms inference, 0.0ms loss, 4.5ms postprocess per image

   conf  precision_B  recall_B   map50_B  map50_95_B      f1_B
0  0.05     0.758410  0.789630  0.846767    0.733209  0.773705
1  0.10     0.758410  0.789630  0.838266    0.727948  0.773705
2  0.15     0.758410  0.789630  0.835170    0.727642  0.773705
3  0.20     0.758410  0.789630  0.836399    0.729409  0.773705
4  0.25     0.758410  0.789630  0.836230    0.730139  0.773705
5  0.30     0.758410  0.789630  0.833136    0.728634  0.773705
6  0.35     0.758410  0.789630  0.828374    0.726084  0.773705
8  0.50     0.789678  0.738635  0.799365    0.697924  0.763304
7  0.40     0.790031  0.733362  0.803983    0.700687  0.760643